name = "Skyfall Survival"
author = "tay"
version = "12.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "979b3177e2ed96def2a4a539ff9aa2db7f0044ce50e6a5f77360c22a352f97b9"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
