name = "Skyfall Survival"
author = "tay"
version = "12.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "74b4f130739206bae7ff3d98b39f749cfc2a1c96c19b12414f91be9479020ac1"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
