name = "Skyfall Survival"
author = "tay"
version = "12.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "855feafc8f4291947fd15a4e66dba6adcb59bf7d7e2d71003499f9b4822fb8bc"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
